title: Crystal Dixson
logo: /assets/img/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  **Hi, my name is Crystal! I am currently located in Portland, Oregon. I have completed the Data Science program at Lambda School and I have a degree in Applied Linguistics from Portland State University.**
  <br><br>
  **I have experience with Python, SQL, Statistics, Data Visualizations and Machine Learning. Currently I am learning Neural Networks and Natural Language Processing.**
  <br><br>
  
  <a href="mailto:crystal.dixson@gmail.com">Send me an email</a>
  
  <br><br>
  <a href="https://www.linkedin.com/in/crystaldixson/">View My LinkedIn Profile</a> 

show_downloads: false
google_analytics: G-V6JHG6DXRN
theme: jekyll-theme-minimal
